import { StyleSheet } from 'react-native';
import { BUTTON_ACTION, BUTTON_ACTION_TEXT, WHITE, ORANGE, BLUE } from './common';

export const button = StyleSheet.create({
  // container: {
  //   borderRadius: 5,
  // },
  button: {
    backgroundColor: BUTTON_ACTION,
    color: BUTTON_ACTION_TEXT,
    borderRadius: 5,
    padding: 15,
    shadowColor: 'transparent',
    shadowOpacity: 0,
  },
  greetingButton: {
    borderRadius: 80,
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: WHITE,
    shadowColor: 'transparent',
    shadowOpacity: 0,
    // borderWidth: 1,
    borderColor: '#fff',
    overflow: 'hidden',
  },
  sessionButton: {
    borderRadius: 80,
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: ORANGE,
    shadowColor: 'transparent',
    shadowOpacity: 0,
    // borderWidth: 1,
    borderColor: '#fff',
    width: 200,
    overflow: 'hidden',
    // alignSelf: 'stretch',
    // textAlign: 'center',
  },
  negFormButton: {
    borderRadius: 80,
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderWidth: 3,
    borderColor: BLUE,
    width: 120,
    overflow: 'hidden',
  },
  posFormButton: {
    borderRadius: 80,
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: BLUE,
    borderWidth: 3,
    borderColor: BLUE,
    maxWidth: 140,
    overflow: 'hidden',
  },
  posFormButtonDash: {
    borderRadius: 80,
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: BLUE,
    borderWidth: 3,
    borderColor: BLUE,
    maxWidth: 400,
    overflow: 'hidden',
  },
  negFormButtonRecipe: {
    borderRadius: 80,
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderWidth: 3,
    borderColor: BLUE,
    // alignItems: 'stretch',
    width: 180,
    overflow: 'hidden',
  },
  posFormButtonRecipe: {
    borderRadius: 80,
    marginTop: 20,
    alignSelf: 'center',
    backgroundColor: BLUE,
    borderWidth: 3,
    borderColor: BLUE,
    // alignItems: 'stretch',
    width: 180,
    overflow: 'hidden',
  },
});

export const back = StyleSheet.create({
  container: {
    flex: 1, 
    flexDirection: 'row', 
    alignContent: 'flex-start', 
    justifyContent: 'space-between', 
    alignItems: 'flex-start',
    // backgroundColor: 'white'
  },
  containerCamera: {
    // flex: 1, 
    flexDirection: 'row', 
    alignContent: 'flex-start', 
    justifyContent: 'space-between', 
    alignItems: 'flex-start',
    // backgroundColor: 'transparent',
    // height: 100,
    // width: null,
  },
});
